import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import Link from "next/link";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <div class="p-5 bg-primary text-white text-center">
          <h1>My First Bootstrap 5 Page</h1>
          <p>Resize this responsive page to see the effect!</p>
        </div>
        <nav class="navbar navbar-expand-sm bg-light mb-5">
          <div class="container-fluid">
            <ul class="navbar-nav">
              <li class="nav-item">
                <Link class="nav-link" href="/">Home</Link>
              </li>
              <li class="nav-item">
                <Link class="nav-link" href="/about">About</Link>
              </li>
              <li class="nav-item">
                <Link class="nav-link" href="/blog">Blog</Link>
              </li>
               <li class="nav-item">
                <Link class="nav-link" href="/contact">Contact</Link>
              </li>
            </ul>
          </div>

        </nav>
        <div className="container">
          {children}
        </div>


        <div class="mt-5 p-4 bg-dark text-white text-center">
          <p>Footer</p>
        </div>

      </body>
    </html>
  );
}






